name: Firebase Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Firebase GitHub Action
      uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: "ktp-schedule-planner"
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy
